# Configuration for Varied Entanglement Experiments (Fahad Abdullah)
experiment_name: "varied_entanglement"
researcher: "Fahad Abdullah"

# Quantum Network Configuration
n_qubits: 4
n_layers: 3
n_rotations: 3
entanglement_type: "varied"
entanglement_strength: 0.5
measurement_type: "expval"
backend: "default.qubit"
shots: null

# Training Configuration
epochs: 50
batch_size: 32
learning_rate: 0.001
patience: 10
train_split: 0.8

# Barren Plateau Analysis
barren_plateau_threshold: 1e-6
gradient_analysis_epochs: 10

# Data Configuration
dataset: "FashionMNIST"
input_size: 784
num_classes: 10

# Logging and Saving
save_dir: "./results/varied_entanglement"
log_interval: 10
save_interval: 5
use_wandb: true
wandb_project: "Hybrid-QNNs"
wandb_entity: null

# Hardware Configuration
device: "auto"
num_workers: 4
pin_memory: true
